name: Run contract tests

on: push

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_BRANCH: ${{ github.ref_name }}

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm i
      - name: Run web consumer contract tests
        run: npm run test:web:consumer
      - name: Run graphql consumer contract tests
        run: npm run test:graphql:consumer
      - name: Publish contract to Pactflow
        run: npm run publish:pact
      - name: Run provider contract tests
        run: npm run test:provider
      - name: Run graphql provider contract tests
        run: npm run test:graphql:provider
      - name: Can I deploy web consumer?
        run: npm run can:i:deploy:consumer
      - name: Can I deploy GraphQL consumer?
        run: npm run can:i:deploy:graphql:consumer
      - name: Can I deploy provider?
        run: npm run can:i:deploy:provider
      - name: Can I deploy GraphQL provider?
        run: npm run can:i:deploy:graphql:provider
      - name: Record web consumer deployment
        run: npm run record:web:consumer:deployment
        if: ${{ github.ref_name == 'main' }}
      - name: Record provider deployment
        run: npm run record:provider:deployment
        if: ${{ github.ref_name == 'main' }}
      - name: Record GraphQL consumer deployment
        run: npm run record:graphql:consumer:deployment
        if: ${{ github.ref_name == 'main' }}
      - name: Record GraphQL provider deployment
        run: npm run record:graphql:provider:deployment
        if: ${{ github.ref_name == 'main' }}